## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values. 

In [3]:
import numpy as np

a = np.array([[1.1, 2.2, 3.3, 4.4, 5.5, 6.6], [1.1, 2.2, 3.3, 4.4, 5.5, 6.6], [1.1, 2.2, 3.3, 4.4, 5.5, 6.6]])
a

array([[1.1, 2.2, 3.3, 4.4, 5.5, 6.6],
       [1.1, 2.2, 3.3, 4.4, 5.5, 6.6],
       [1.1, 2.2, 3.3, 4.4, 5.5, 6.6]])

Check the dimension you have created is correct (use “*.shape*”)

In [4]:
a.shape

(3, 6)

Substitute the 5th element from the 2nd row with 19.75.

In [7]:
a[1,4] = 19.75
a

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ,  6.6 ],
       [ 1.1 ,  2.2 ,  3.3 ,  4.4 , 19.75,  6.6 ],
       [ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 , 19.75]])

Extract the 2nd and the 3rd row of the array you created. 

In [11]:
a[1:3]

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 , 19.75,  6.6 ],
       [ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 , 19.75]])