# Linear Algebra

In [1]:
import numpy as np 

In [3]:
v = np.array([3,2])
print(v)

[3 2]


In [4]:
v = np.array([4,1,2])
print(v)

[4 1 2]


In [5]:
v = np.array([6,1,5,8,3])
print(v)

[6 1 5 8 3]


In [8]:
v = np.array([3,2])
w = np.array([2,-1])

#sum vectors
v_plus_w = v + w

print(v_plus_w)

[5 1]


#### Scaling 

In [9]:
v = np.array([3,1])

#Scale the vector
scaled_v = 2.0 * v

print(scaled_v)

[6. 2.]


In [10]:
# matrix = collection of vectors

#Four movements can be achived with linear tranformation 
#SCALE = [1,2]
#ROTATE = [-1, 1]
#SHEAR = [2, 1]
#INVERSION = [1, 1]

#### Multiplication 

In [11]:
from numpy import array

In [13]:
#compose basis matrix with i-hat and j-hat
basis = array([[3,0],[0,2]])

#vector v
v = array([1,1])

#create new vector
#by tranforming v with dot product 
new_v = basis.dot(v)

print(new_v)

[3 2]


In [24]:
i_hat = array([2,0])
j_hat = array([0,3])

#compose basis matrix using i_hat and j_hat
#also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

#declare vector v 
v = array([1,1])

#create new vector
#by tranforming v with dot product 
new_v = basis.dot(v)


print(new_v)

[2 3]


In [30]:
i_hat = array([2,0])
j_hat = array([0,3])

#compose basis matrix using i_hat and j_hat
#also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

#declare vector v 
v = array([2,1])

#create new vector
#by tranforming v with dot product 
new_v = basis.dot(v)


print(new_v)

[4 3]


In [31]:
i_hat = array([2,3])
j_hat = array([2,-1])

#compose basis matrix using i_hat and j_hat
#also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

#declare vector v 
v = array([2,1])

#create new vector
#by tranforming v with dot product 
new_v = basis.dot(v)


print(new_v)

[6 5]


In [ ]:
#APPLYING ROTATION AND THEN SHEAT TO ANY VECTOR

#[1 1] [0 -1] [x]
# 0 1   1  0   y

In [37]:
#Transformation1
i_hat1 = array([0,1])
j_hat1 = array([-1,0])
transform1 = array([i_hat1, j_hat1]).transpose()

#Transformation2
i_hat2 = array([1,0])
j_hat2 = array([1,1])
transform2 = array([i_hat2, j_hat2]).transpose()

#Combined
combined = transform2 @ transform1

print(f"Combined Matrix: {combined}")

#declare vector v 
v = array([1,2])

new_v = combined.dot(v)


print(new_v)

Combined Matrix: [[ 1 -1]
 [ 1  0]]
[-1  1]


In [44]:
#Tranformation in reverse

#Transformation1
i_hat1 = array([0,1])
j_hat1 = array([-1,0])
transform1 = array([i_hat1, j_hat1]).transpose()

#Transformation2
i_hat2 = array([1,0])
j_hat2 = array([1,1])
transform2 = array([i_hat2, j_hat2]).transpose()

#Combined
combined = transform1 @ transform2

print(f"Combined Matrix: {combined}")

#declare vector v 
v = array([1,2])

new_v = combined.dot(v)


print(new_v)

Combined Matrix: [[ 0 -1]
 [ 1  1]]
[-2  3]


### Determinants 

In [45]:
#Determinant = describe how much a sampled area in a vector space changes in scale with linear tranformations

In [46]:
from numpy.linalg import det
from numpy import array

In [48]:
i_hat = array([3,0])
j_hat = array([0,2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

6.0


In [49]:
np.linalg.det(basis)

6.0

In [50]:
i_hat = array([1,0])
j_hat = array([1,1])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

1.0


In [53]:
#Negative determinant - the orientation has flipped

i_hat = array([-2,1])
j_hat = array([1,2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

-5.000000000000001


In [54]:
#Determinant = 0 -- means all of the space has been squished into a lesser dimension

In [55]:
#Linear dependence

i_hat = array([3,-1.5])
j_hat = array([-2,1])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

0.0


### Matrix

In [1]:
# Ax = b
# AX =B
# A**-1 AX = A**-1 B
# X = A**-1 B

In [8]:
#Using Sympy

from sympy import *

A = Matrix ([[4,2,4],[5,3,7],[9,3,6]])

#dot product
inverse = A.inv()
identity = inverse * A

print(f"Inverse: {inverse}")
print(f"Identity: {identity}")

Inverse: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
Identity: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [10]:
#with numpy
import numpy as np

A = np.array ([
    [4,2,4],
    [5,3,7],
    [9,3,6]
])

b = np.array([
    44,
    56,
    72
])

x = np.linalg.inv(A).dot(b)

print(x)
#Values of x , y and z

[ 2. 34. -8.]


### Eigenvectors and Eigenvalues 

In [11]:
#braking up a matrix into components that are easier to work with in different machine learning tasks

#Av = lambda*v

In [12]:
from numpy import array, diag
from numpy.linalg import eig, inv

In [14]:
A = np.array ([
    [1,2],
    [4,5],
])

eigenvals, eigenvecs = eig(A)

print(f"Eigenvalues: {eigenvals}")
print(f"Eigenvectors: {eigenvecs}")

Eigenvalues: [-0.46410162  6.46410162]
Eigenvectors: [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [16]:
# A = Q * L * Q**-1

#Q = eigenvectors
#L = Diagonal of Egenvalues

In [18]:
Q = eigenvecs
R = inv(Q)

L = diag(eigenvals)
B = Q @ L @ R

print(f"Matrix A = {B}")

Matrix A = [[1. 2.]
 [4. 5.]]


In [20]:
L 

array([[-0.46410162,  0.        ],
       [ 0.        ,  6.46410162]])